#!/bin/sh -u

echo "*** Filebot is watching on $1 folder ***"
inotifywait -m "$1" -e create -e moved_to -e modify --exclude '/[.@]' --format '%w%f' | stdbuf -oL uniq | while read -r FILE; do
	# file may yield inode/x-empty for new files
	sleep 2

	# abort if the file has been modified while we were asleep
	if [ `find "$FILE" -type f -newermt '2 seconds ago' -print -quit` ]; then
		echo "Modified: $FILE"
		continue
	fi

	# e.g. video.mp4: video/mp4
	if file --mime-type "$FILE" | egrep "directory|video|audio|empty|octet-stream"; then
		filebot -script fn:amc --action duplicate --conflict auto -non-strict --log-file amc.log --def excludeList=".excludes" unsorted=y music=y artwork=y "$@"
		rc=$?	
		filebot -script fn:cleaner "$1"
		if [[ $rc != 0 ]]; then		
			cat /data/filebot.log | mutt -F /muttrc -s 'Filebot Error' canibis313@gmail.com
		else
			cat /data/filebot.log | mutt -F /muttrc -s 'Filebot successfully ended' canibis313@gmail.com
		fi
		rm -rf /data/filebot.log
	fi
done
